// Auto-generated from OpenAPI specification
// Do not edit this file manually

export enum HttpMethod {
  GET = 'GET',
  POST = 'POST',
  PUT = 'PUT',
  PATCH = 'PATCH',
  DELETE = 'DELETE',
  HEAD = 'HEAD',
  OPTIONS = 'OPTIONS',
  TRACE = 'TRACE',
}

export const OperationId = {
  createPet: 'createPet',
  deletePet: 'deletePet',
  getPet: 'getPet',
  listPets: 'listPets',
  listUserPets: 'listUserPets',
  updatePet: 'updatePet',
} as const

export type OperationId = (typeof OperationId)[keyof typeof OperationId]

export const OPERATION_INFO = {
  createPet: {
    path: '/pets',
    method: HttpMethod.POST,
  },
  deletePet: {
    path: '/pets/{petId}',
    method: HttpMethod.DELETE,
  },
  getPet: {
    path: '/pets/{petId}',
    method: HttpMethod.GET,
  },
  listPets: {
    path: '/pets',
    method: HttpMethod.GET,
  },
  listUserPets: {
    path: '/users/{userId}/pets',
    method: HttpMethod.GET,
  },
  updatePet: {
    path: '/pets/{petId}',
    method: HttpMethod.PUT,
  },
} as const
