// Auto-generated from OpenAPI specification
// Do not edit this file manually

/**
 * Enum values from components.schemas.Pet.properties.status
 */
export const PetStatus = {
  Adopted: 'adopted' as const,
  Available: 'available' as const,
  Pending: 'pending' as const,
} as const

export type PetStatus = (typeof PetStatus)[keyof typeof PetStatus]
