/* eslint-disable */
// Auto-generated from OpenAPI specification
// Do not edit this file manually

import type { components } from './openapi-types'
import type { RequireAll } from '@qualisero/openapi-endpoint'

/**
 * Direction-typed schema aliases generated from the OpenAPI spec.
 *
 * ## Responses namespace
 * Contains only the **response-reachable** component set — the transitive $ref
 * closure seeded from all operation response bodies. Each member is wrapped in
 * `RequireAll<T>`, asserting that the API serialises every documented field
 * (same policy as `ApiResponse` / `Types.<opId>.Response`).
 * For spec-fidelity without the serialise-everything assumption, use
 * `Types.<opId>.StrictResponse` instead.
 *
 * ## Bare aliases (below)
 * Direction-blind: they expose `components['schemas']` without a presence policy.
 * Kept for one minor cycle with `@deprecated` tags indicating the direction-typed
 * replacement. They will be removed in the next major release.
 *
 * ## Request direction
 * Request bodies are operation-shaped. Use `Types.<opId>.Request` — there is
 * intentionally no `Requests` namespace.
 *
 * @example
 * import type { Responses } from './api-schemas'
 * const pet: Responses.Pet = response.data
 */

export namespace Responses {
  /** Referenced by: listPets (items), createPet (response), getPet (response), updatePet (response), uploadPetPic (response), searchPets (items), listUserPets (items), getPetPetId (response), updatePetPetId (response), postPetAdopt (response) */
  export type Pet = RequireAll<components['schemas']['Pet']>
}

/** @deprecated Use Types.createPet.Request, Types.updatePet.Request, Types.updatePetPetId.Request instead. */
export type NewPet = components['schemas']['NewPet']

/** @deprecated Use Responses.Pet instead. */
export type Pet = components['schemas']['Pet']

/** @deprecated Use Types.uploadPetPic.Request instead. */
export type SingleFile = components['schemas']['SingleFile']
