// Auto-generated from OpenAPI specification
// Do not edit this file manually

import type { components } from './openapi-types.js'

/**
 * Type aliases for schema objects from the API spec.
 * These are references to components['schemas'] for convenient importing.
 *
 * @example
 * import type { Nuts, Address, BorrowerInfo } from './api-schemas'
 *
 * const nutsData: Nuts = { NUTS_ID: 'BE241', ... }
 */

export type NewPet = components['schemas']['NewPet']

export type Pet = components['schemas']['Pet']

export type SingleFile = components['schemas']['SingleFile']
