// Auto-generated from OpenAPI specification
// Do not edit this file manually

/**
 * Generic utility for working with enums
 *
 * @example
 * import { EnumHelper, RequestedValuationType } from './api-enums'
 *
 * // Get all values
 * const allTypes = EnumHelper.values(RequestedValuationType)
 *
 * // Validate a value
 * if (EnumHelper.isValid(RequestedValuationType, userInput)) {
 *   // TypeScript knows userInput is RequestedValuationType
 * }
 *
 * // Reverse lookup
 * const key = EnumHelper.getKey(RequestedValuationType, 'cat') // 'Cat'
 */
export const EnumHelper = {
  /**
   * Get all enum values as an array
   */
  values<T extends Record<string, string | number>>(enumObj: T): Array<T[keyof T]> {
    return Object.values(enumObj) as Array<T[keyof T]>
  },

  /**
   * Get all enum keys as an array
   */
  keys<T extends Record<string, string | number>>(enumObj: T): Array<keyof T> {
    return Object.keys(enumObj) as Array<keyof T>
  },

  /**
   * Check if a value is valid for the given enum
   */
  isValid<T extends Record<string, string | number>>(enumObj: T, value: unknown): value is T[keyof T] {
    return typeof value === 'string' && (Object.values(enumObj) as string[]).includes(value)
  },

  /**
   * Get the enum key from a value (reverse lookup)
   */
  getKey<T extends Record<string, string | number>>(enumObj: T, value: T[keyof T]): keyof T | undefined {
    const entry = Object.entries(enumObj).find(([_, v]) => v === value)
    return entry?.[0] as keyof T | undefined
  },
} as const

/**
 * Enum values from components.schemas.Pet.properties.status
 */
export const PetStatus = {
  Adopted: 'adopted' as const,
  Available: 'available' as const,
  Pending: 'pending' as const,
} as const

export type PetStatus = (typeof PetStatus)[keyof typeof PetStatus]

// Type aliases for duplicate enum values
export const NewPetStatus = PetStatus
export type NewPetStatus = PetStatus
