/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/pets': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List all pets */
    get: operations['listPets']
    put?: never
    /** Create a new pet */
    post: operations['createPet']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/pets/{petId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get a pet by ID */
    get: operations['getPet']
    /** Update a pet */
    put: operations['updatePet']
    post?: never
    /** Delete a pet */
    delete: operations['deletePet']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/pets/{petId}/upload': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Upload a picture for a pet */
    post: operations['uploadPetPic']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/users/{userId}/pets': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List pets for a specific user */
    get: operations['listUserPets']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/pet/{pet_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get a pet by ID (no operationId) */
    get: operations['getPetPetId']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /** Partially update a pet (no operationId) */
    patch: operations['updatePetPetId']
    trace?: never
  }
  '/api/pet/{pet_id}/adopt': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Adopt a pet (no operationId) */
    post: operations['postPetAdopt']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/owners': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List all owners (no operationId) */
    get: operations['getOwners']
    put?: never
    /** Create a new owner (no operationId) */
    post: operations['postOwners']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/pet/give_treats': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Give treats to pets (no operationId, tests snake_case conversion) */
    post: operations['postPetGiveTreats']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/config.json': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get config file (tests file extension handling) */
    get: operations['getConfigJson']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/data.v1.json': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get data file with periods (tests period handling) */
    get: operations['getDataV1Json']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    Pet: {
      /** Format: uuid */
      readonly id?: string
      name: string
      tag?: string
      /** @enum {string} */
      status?: 'available' | 'pending' | 'adopted'
    }
    NewPet: {
      name: string
      tag?: string
      /** @enum {string} */
      status?: 'available' | 'pending' | 'adopted'
    }
    SingleFile: {
      /** Format: binary */
      file: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  listPets: {
    parameters: {
      query?: {
        limit?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description A list of pets */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Pet'][]
        }
      }
    }
  }
  createPet: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['NewPet']
      }
    }
    responses: {
      /** @description Pet created successfully */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Pet']
        }
      }
    }
  }
  getPet: {
    parameters: {
      query?: never
      header?: never
      path: {
        petId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Pet details */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Pet']
        }
      }
    }
  }
  updatePet: {
    parameters: {
      query?: never
      header?: never
      path: {
        petId: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['NewPet']
      }
    }
    responses: {
      /** @description Pet updated successfully */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Pet']
        }
      }
    }
  }
  deletePet: {
    parameters: {
      query?: never
      header?: never
      path: {
        petId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Pet deleted successfully */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            message?: string
          }
        }
      }
    }
  }
  uploadPetPic: {
    parameters: {
      query?: never
      header?: never
      path: {
        petId: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['SingleFile']
      }
    }
    responses: {
      /** @description Picture uploaded successfully */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Pet']
        }
      }
      /** @description Unprocessable content */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            message?: string
          }
        }
      }
      /** @description Default error response */
      default: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            message?: string
          }
        }
      }
    }
  }
  listUserPets: {
    parameters: {
      query?: never
      header?: never
      path: {
        userId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description A list of user pets */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Pet'][]
        }
      }
    }
  }
  getPetPetId: {
    parameters: {
      query?: never
      header?: never
      path: {
        pet_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Pet details */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Pet']
        }
      }
    }
  }
  updatePetPetId: {
    parameters: {
      query?: never
      header?: never
      path: {
        pet_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['NewPet']
      }
    }
    responses: {
      /** @description Pet updated successfully */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Pet']
        }
      }
    }
  }
  postPetAdopt: {
    parameters: {
      query?: never
      header?: never
      path: {
        pet_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': {
          adopterId?: string
        }
      }
    }
    responses: {
      /** @description Pet adopted successfully */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Pet']
        }
      }
    }
  }
  getOwners: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description A list of owners */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            id?: string
            name?: string
          }[]
        }
      }
    }
  }
  postOwners: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': {
          name?: string
        }
      }
    }
    responses: {
      /** @description Owner created successfully */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            id?: string
            name?: string
          }
        }
      }
    }
  }
  postPetGiveTreats: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': {
          treatType?: string
          quantity?: number
        }
      }
    }
    responses: {
      /** @description Treats given successfully */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            message?: string
          }
        }
      }
    }
  }
  getConfigJson: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Config file */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': Record<string, never>
        }
      }
    }
  }
  getDataV1Json: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Data file */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': Record<string, never>
        }
      }
    }
  }
}
