// Auto-generated from OpenAPI specification
// Do not edit this file manually

import type { operations } from './openapi-types'

export enum HttpMethod {
  GET = 'GET',
  POST = 'POST',
  PUT = 'PUT',
  PATCH = 'PATCH',
  DELETE = 'DELETE',
  HEAD = 'HEAD',
  OPTIONS = 'OPTIONS',
  TRACE = 'TRACE',
}

// Create the typed structure that combines operations with operation metadata
// This ensures the debug method returns correct values and all operations are properly typed
const operationsBase = {
  createPet: {
    path: '/pets',
    method: HttpMethod.POST,
  },
  deletePet: {
    path: '/pets/{petId}',
    method: HttpMethod.DELETE,
  },
  getPet: {
    path: '/pets/{petId}',
    method: HttpMethod.GET,
  },
  listPets: {
    path: '/pets',
    method: HttpMethod.GET,
  },
  listUserPets: {
    path: '/users/{userId}/pets',
    method: HttpMethod.GET,
  },
  updatePet: {
    path: '/pets/{petId}',
    method: HttpMethod.PUT,
  },
  uploadPetPic: {
    path: '/pets/{petId}/upload',
    method: HttpMethod.POST,
  },
} as const

// Merge with operations type to maintain OpenAPI type information
export const openApiOperations = operationsBase as typeof operationsBase & operations

export type OpenApiOperations = typeof openApiOperations

// Dynamically generate OperationId enum from the operations keys
export const OperationId = {
  createPet: 'createPet' as const,
  deletePet: 'deletePet' as const,
  getPet: 'getPet' as const,
  listPets: 'listPets' as const,
  listUserPets: 'listUserPets' as const,
  updatePet: 'updatePet' as const,
  uploadPetPic: 'uploadPetPic' as const,
} satisfies Record<keyof typeof operationsBase, keyof typeof operationsBase>

// Export the type for TypeScript inference
export type OperationId = keyof OpenApiOperations
