// Auto-generated from OpenAPI specification
// Do not edit this file manually

import type { operations } from './openapi-types'
import type {
  ApiResponse as ApiResponseBase,
  ApiRequest as ApiRequestBase,
  ApiPathParams as ApiPathParamsBase,
  ApiQueryParams as ApiQueryParamsBase,
} from '@/types'

export enum HttpMethod {
  GET = 'GET',
  POST = 'POST',
  PUT = 'PUT',
  PATCH = 'PATCH',
  DELETE = 'DELETE',
  HEAD = 'HEAD',
  OPTIONS = 'OPTIONS',
  TRACE = 'TRACE',
}

// Create the typed structure that combines operations with operation metadata
// This ensures the debug method returns correct values and all operations are properly typed
const operationsBase = {
  createPet: {
    path: '/pets',
    method: HttpMethod.POST,
  },
  deletePet: {
    path: '/pets/{petId}',
    method: HttpMethod.DELETE,
  },
  getPet: {
    path: '/pets/{petId}',
    method: HttpMethod.GET,
  },
  listPets: {
    path: '/pets',
    method: HttpMethod.GET,
  },
  listUserPets: {
    path: '/users/{userId}/pets',
    method: HttpMethod.GET,
  },
  updatePet: {
    path: '/pets/{petId}',
    method: HttpMethod.PUT,
  },
  uploadPetPic: {
    path: '/pets/{petId}/upload',
    method: HttpMethod.POST,
  },
} as const

// Merge with operations type to maintain OpenAPI type information
export const openApiOperations = operationsBase as typeof operationsBase & operations

export type OpenApiOperations = typeof openApiOperations

// Dynamically generate OperationId enum from the operations keys
export const OperationId = {
  createPet: 'createPet' as const,
  deletePet: 'deletePet' as const,
  getPet: 'getPet' as const,
  listPets: 'listPets' as const,
  listUserPets: 'listUserPets' as const,
  updatePet: 'updatePet' as const,
  uploadPetPic: 'uploadPetPic' as const,
} satisfies Record<keyof typeof operationsBase, keyof typeof operationsBase>

// Export the type for TypeScript inference
export type OperationId = keyof OpenApiOperations

// ============================================================================
// Type-safe API Helpers - Use OpType.XXX for type-safe access with intellisense
// ============================================================================

/**
 * Response data type for an API operation.
 * @example
 *   type Response = ApiResponse<OpType.getPet>
 */
export type ApiResponse<K extends OperationId> = ApiResponseBase<OpenApiOperations, K>

/**
 * Request body type for a mutation operation.
 * @example
 *   type Request = ApiRequest<OpType.createPet>
 */
export type ApiRequest<K extends OperationId> = ApiRequestBase<OpenApiOperations, K>

/**
 * Path parameters type for an operation.
 * @example
 *   type Params = ApiPathParams<OpType.getPet>
 */
export type ApiPathParams<K extends OperationId> = ApiPathParamsBase<OpenApiOperations, K>

/**
 * Query parameters type for an operation.
 * @example
 *   type Params = ApiQueryParams<OpType.listPets>
 */
export type ApiQueryParams<K extends OperationId> = ApiQueryParamsBase<OpenApiOperations, K>

// ============================================================================
// OpType namespace - enables dot notation: ApiResponse<OpType.getPet>
// ============================================================================

/**
 * Namespace that mirrors OperationId properties as types.
 * Enables dot notation syntax: ApiResponse<OpType.getPet>
 *
 * This is the idiomatic TypeScript pattern for enabling dot notation
 * on type-level properties. The namespace is preferred over type aliases
 * because it allows `OpType.getPet` instead of `OpType['getPet']`.
 *
 * @example
 *   type Response = ApiResponse<OpType.getPet>
 *   type Request = ApiRequest<OpType.createPet>
 */
// eslint-disable-next-line @typescript-eslint/no-namespace
export namespace OpType {
  export type getPet = typeof OperationId.getPet
  export type createPet = typeof OperationId.createPet
  export type updatePet = typeof OperationId.updatePet
  export type deletePet = typeof OperationId.deletePet
  export type listPets = typeof OperationId.listPets
  export type listUserPets = typeof OperationId.listUserPets
  export type uploadPetPic = typeof OperationId.uploadPetPic
}
